### ISSUE TITLE
Research imdb API

### ISSUE THREAD

**Issue by Kaloyan-Stankov** [SoundofGoodbye/movie-crawler#8]
If there's not such a thing do find someone find another one.

**Comment by SoundofGoodbye** [comment]
Performed research on TMDB api:

To enable WebApp to make request simply provide api key
Example request: https://api.themoviedb.org/3/movie/76341?api_key={api_key}

We can get the images (posters) for specific movie: You'll notice that movie, TV and person objects contain references to different file paths. In order to generate a fully working image URL, 
you'll need 3 pieces of data. Those pieces are a base_url, a file_size and a file_path.
Example: https://image.tmdb.org/t/p/w500/kqjL17yufvn9OVLyXYpvtyrFfak.jpg

Regions support - we can filter for a movie to find it's release date for specific region like germany (when the movie will be released in germany)
https://api.themoviedb.org/3/search/movie?api_key=<<api_key>>&query=whiplash&language=de-DE&region=DE
There is also a release type - Premiere, Theatrical (limited), Theatrical, Digital, Physical, TV
https://api.themoviedb.org/3/discover/movie?api_key=<<api_key>>&language=de-DE&region=DE&release_date.gte=2016-11-16&release_date.lte=2016-12-02&with_release_type=2|3

Request rate limit: You can use the X-RateLimit headers that get returned with every request to keep track of your current limits. 
If you exceed the limit, you will receive a 429 HTTP status with a Retry-After header. As soon your cool down period expires, you are free to continue making requests.

Even more powerful, you can issue multiple requests, just comma separate the values:

https://api.themoviedb.org/3/movie/157336?api_key={api_key}&append_to_response=videos,images
The best part of this is that these requests only count as one request against the rate limits so you can really speed up your experience.
